{% set version = "2.1-2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-labdsv
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/labdsv_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/labdsv/labdsv_{{ version }}.tar.gz
  sha256: 31322f5e820cc0bfcc7b87cc1835a265dfc9bbfe4b3f420e427889856469fa58

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-mass                       # [build_platform != target_platform]
    - r-rtsne                      # [build_platform != target_platform]
    - r-cluster                    # [build_platform != target_platform]
    - r-mgcv                       # [build_platform != target_platform]
  host:
    - r-base
    - r-mass
    - r-rtsne
    - r-cluster
    - r-mgcv
  run:
    - r-base
    - r-mass
    - r-rtsne
    - r-cluster
    - r-mgcv

test:
  commands:
    - $R -e "library('labdsv')"           # [not win]
    - "\"%R%\" -e \"library('labdsv')\""  # [win]

about:
  home: http://ecology.msu.montana.edu/labdsv/R
  license: GPL-2.0-or-later
  summary: A variety of ordination and community analyses useful in analysis of data sets in community ecology.   Includes many of the common ordination methods, with  graphical routines to facilitate their interpretation,  as well as several novel analyses.
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - nsoranzo

# Package: labdsv
# Version: 2.0-1
# Title: Ordination and Multivariate Analysis for Ecology
# Author: David W. Roberts <droberts@montana.edu>
# Maintainer: David W. Roberts <droberts@montana.edu>
# Depends: R (>= 2.10), mgcv
# Imports: cluster, Rtsne, MASS
# Suggests: optpart
# Enhances: vegan
# Description: A variety of ordination and community analyses useful in analysis of data sets in community ecology.   Includes many of the common ordination methods, with  graphical routines to facilitate their interpretation,  as well as several novel analyses.
# License: GPL (>= 2)
# URL: http://ecology.msu.montana.edu/labdsv/R
# Packaged: 2019-08-04 10:08:57 UTC; dvrbts
# NeedsCompilation: yes
# Repository: CRAN
# Date/Publication: 2019-08-04 12:00:02 UTC
