# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Sp3O50h9JeXCbii2s+b1sWmgyyYXSr7q+cCf1iuK5Zqlg1FulCsvp+96ubEjFu/uACR9ebCJlvWSj23REXZxI6Bcxt+MPivZO3DyfRvzPdFI2YmjlYrA4qK+V/hvCeg2Qaodxsj1BJPgWCgFjc2yCOWOgkrhlXOIUgfI3hRdT4F9DQi2zvvT+e9HQbMUSHMP6zREQV6bA+faJChAgz310L6bijtpJgSiJZCDrj7aGU9AvA/zkO3WGig8zWnBOVOQGL0NLdc0Fi+F9Gc4fmGRyJq2BA7fAOVtWMImq3a/k5iYR6Fjs5XbpuEaP3ZkuJ6dtiaB4BZTiyQpcC/rdrHVOb8C14am5uHkqNY7eZG2e8oP8PSFTBnZPvmgWoCS+OSWbzKALd3DaPXvxqNbF61JxGFEtrw2PipLmP0ytp+FOt2IxBqeG8NIpHlh9O+eRJCNehxMZkZt817cwlzQnF+Yqn8msV2OEctFCOqOkPJTLaqS0qUnT8cTsPAkLEFTvY6Kh3CEMcIgpma9WcbJPenEMvjlkRqRil+cZUDCsBTiJ2KmxvuSu/gGfyGaDTIABw9vyCgKqP11z/7JUcoZRZvq0JWWtO0Q/kiwvKqf77IB83AuZMl/cCqjejAkLGfSwLZyQKHchpldCX4d6oMrFA0QzJEg6vg0RjEub3kKQ5ew86w="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
