appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: RguGU2Q0191VflrRQSQbo73gDrLUprUKs+gCsAL/DUEc/hKSvMbVetl6f734DDEfdJxpa14PamEeTmHMsj6F4RjWCLZZ2zXAeo3sCzOupcO+NtIG846AYmUsevnSa8yBb5CNe94ojaW6sEDtq9tp4iK1RbSnSbCy6taD4opoHuVG/QKC3+zERPh1VkbKsshVO7Dm0VXDNZzt0pTt2cEvlllKFFvGkNELvh5VXJtoNwVPDRy+OSQzsjbugaRQO0MUWw8q/uWeiK9OV+K9MUr+5T5wRJzdLOEadu64h2Ya+6+NQMBUK0erDzTqeAxakI9SuJbmfxdu06Lp7zYOuG5OURufxJ+Q2aaZyB05JFKqxRiUPjOG/mlhChp6fidS2Lugmmq0KpDqQZ5DGDiknQ+kTZXmE6MbNnST3f7Yd4loWij3TjeWs3TQbTGbswupKkD60EAQOOms4XdCTDmGxzzrYwXfIUewwHAB/zVHiWMMYFsS+v7dGK8LHfpDK5GHGAw1yQbOSHjDrBL0P+wUT5vNYZSOKByblZ+QyroZ+gbbRQVYofwUROxtetXqEfzrj2EY8803BoD9DqwjniqzUHlRvHOCavdUygDf4rQo1j24EaAjP/pSmZIyQ2/s5Rx0o9vlNjKv3wj75jRzs2RBo9HwWoQDZ2abc6MEajI1ZlH1SYA=}
bot:
  automerge: true
