travis:
  secure:
    BINSTAR_TOKEN: Sp3O50h9JeXCbii2s+b1sWmgyyYXSr7q+cCf1iuK5Zqlg1FulCsvp+96ubEjFu/uACR9ebCJlvWSj23REXZxI6Bcxt+MPivZO3DyfRvzPdFI2YmjlYrA4qK+V/hvCeg2Qaodxsj1BJPgWCgFjc2yCOWOgkrhlXOIUgfI3hRdT4F9DQi2zvvT+e9HQbMUSHMP6zREQV6bA+faJChAgz310L6bijtpJgSiJZCDrj7aGU9AvA/zkO3WGig8zWnBOVOQGL0NLdc0Fi+F9Gc4fmGRyJq2BA7fAOVtWMImq3a/k5iYR6Fjs5XbpuEaP3ZkuJ6dtiaB4BZTiyQpcC/rdrHVOb8C14am5uHkqNY7eZG2e8oP8PSFTBnZPvmgWoCS+OSWbzKALd3DaPXvxqNbF61JxGFEtrw2PipLmP0ytp+FOt2IxBqeG8NIpHlh9O+eRJCNehxMZkZt817cwlzQnF+Yqn8msV2OEctFCOqOkPJTLaqS0qUnT8cTsPAkLEFTvY6Kh3CEMcIgpma9WcbJPenEMvjlkRqRil+cZUDCsBTiJ2KmxvuSu/gGfyGaDTIABw9vyCgKqP11z/7JUcoZRZvq0JWWtO0Q/kiwvKqf77IB83AuZMl/cCqjejAkLGfSwLZyQKHchpldCX4d6oMrFA0QzJEg6vg0RjEub3kKQ5ew86w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
