travis:
  secure:
    BINSTAR_TOKEN: hMI1uYKPTOIJ1TmThe5XJvj59NM50NMqJ2QIzVksvWbg05h9Q8oqb2yNfZHw/6xmqpObCkZ/E/gLP6Vy298fMXaH05d60SR+Qio/nFZt2yzxAKx9Dx1LNYOzlcSmnqZ8t91UGrufHbCuWsoorUHnFI60C5ixwQCn1wbFqgxkcgb/SvMdia5MBq+xOq9FRBRkihpr6RGABbc8PlIanLR48uPhXtbTeaIp8b7pfEogGG2ZPMvY3AF2f2XId7gfOsiuWWzTbSrDt9GOEhUuUCiDQyV26JFutEsBJ8yHUWjgFzhe0+a5oJio44SUXvVwZRtevPPz6pSUpahRkXK5Hb8Z3Y+imZ/UCNX2KQ1H9wWMJy0NM1h3sm2tOL5jtWPDvMHK8ig3l+ZUp8bVpIVfkGbv03/vcx+R3KriJ3qsQgUmkRxFrqrNoFiFlAP6ZFTHvBq44u2+Lkk7nj7A5pw3TUE8zSZjXNUCNCXmMPcap95EqakTa78HRv+uOzv6A6CICHuzAawHWd8WccZGFZiGaxhLDog3XyaSVCZdDgcwj6YQ7fmz/uaAI2dzzHIGV2dBoen0dZCn42tGczSQdzZO4nylLzh1cLUhFhxpe9OD9G69lj8iX2alyIuOA2UerFgP22yhZjFUkrxaACC9M4zgU+/KoXlCyp7fBIerEyZwb6nezXg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
