travis:
  secure:
    BINSTAR_TOKEN: WtSG7MBG+JsE3r0CfxvQWGVAxnlYJdUPDbUaHP9KgcIffu5OzkoGiqQSKwwNJ7Lo97mu9NFQMxqxQhdzASegVJIt65JETq8KknIuMLJWH1SVZSvFS6MUHwIBdYnHiNo/glcNNP9PTjJ+2NuIr2opmkm2dPPZFBbanqypJh0WdLPZT0yluUyPbMbsTQX00SaKbvWJpnpw68aekQtyOS7fl/nGROkAFY/Lo6pxKTnx79UP2PtQokAvXyW798eLIVXMWsLxXiJzfkTPFcT/5CX4vouSVyE790JXvnEbXRt1VCBAhqmwyVNhnj7hlqDSy7xvqjtn3/U7y6qQHmNhHDXapZWmtsc7HDKoZEDFFFZT9/hu15AgkmHmUoeYfyJiXrx+FJfCPCOjtJ47ZppPTHFTyeGvwLwr19zlnL+1jzlJfVWCNGvqp8VXz5zNIs32wmO5mQD22FxH2sd2mDQqgdvKYmiorduLHjOHOrEwFk66lzJaBTPgNwjWIK3PnajpoKikB6Y/QFJMCnLyXqLJPDUKAge7VexJNO4NB+N4/aeu8+e3hDH54Ybn5OazNtzE3Ag5xoL5/IMDkGCgNB93YTV6NIUVlP4JjslpCRTgg2k2Z57sa4k4gUplgwsy13p0BBcQ/Z1bp1DxvohYcWB4VMcdwew980ysfzN6KTwOj8Pxn44=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
